services: 
  develop_db:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: dotnet
      POSTGRES_DB: blogging
      PGDATA: /var/lib/postgresql/data/
    ports:
      - 5432:5432
    volumes:
      - ./.pg-data:/var/lib/postgresql/data/