services: 
  develop_db:
    image: postgres:alpine3.18
    profiles: [development]
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: dotnet
      POSTGRES_DB: blogging
      PGDATA: /var/lib/postgresql/data/
    ports:
      - 5432:5432
    volumes:
      - ./.pg-data:/var/lib/postgresql/data/
  go_service:
    image: gerardohp/testk8s_grpc
    profiles: 
      - development
      - testing
    build:
      context: src/dateService/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  dotnet_service:
    image: gerardohp/testk8s_web
    profiles: [testing]
    build:
      context: src/
      dockerfile: Web/Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      Info__ContainerId: ${HOSTNAME}
      Info__GrpcServiceUrl: http://go_service:8080
      ConnectionStrings__Postgres_Db: "Host=postgres_db;Port=5432;Database=blogging;Username=dotnet;Password=superSecurePassword;"
    depends_on:
      - postgres_db
      - go_service
  postgres_db:
    image: gerardohp/k8stest_db:1.1
    profiles: [testing]
    build:
      context: src/
      dockerfile: ../database.Dockerfile
    environment:
      POSTGRES_PASSWORD: superSecurePassword
      POSTGRES_USER: dotnet
      POSTGRES_DB: blogging
    ports:
      - 5432:5432