apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-service
  labels: 
    app: dotnet-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-service
  template:
    metadata:
      labels:
        app: dotnet-service
    spec:
      containers:
      - name: dotnet-service
        image: gerardohp/testk8s_web:1.3
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        - containerPort: 443
        readinessProbe:
          httpGet:
            path: /api/info/version
            port: 80
        livenessProbe:
          httpGet:
            path: /api/info/proofOfLife
            port: 80
        env:
          - name: Info__ContainerId
            valueFrom:
              fieldRef:
               fieldPath: metadata.name
          - name: ConnectionStrings__Postgres_Db
            valueFrom:
              secretKeyRef:
                key: ConnectionStrings__Postgres_Db
                name: pg-connection
        envFrom:
          - configMapRef:
              name: k8s-test-env
            
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  type: LoadBalancer
  selector:
    app: dotnet-service
  ports:
    - port: 80
      targetPort: 80
      name: regular
    - port: 443
      targetPort: 443
      name: secure
