apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-service
  namespace: test-k8s-app
  labels: 
    app: dotnet-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-service
  template:
    metadata:
      labels:
        app: dotnet-service
    spec:
      containers:
      - name: dotnet-service
        image: gerardohp/testk8s_web
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        - containerPort: 443
        readinessProbe:
          httpGet:
            path: /api/info/version
            port: 80
        livenessProbe:
          httpGet:
            path: /api/info/proofOfLife
            port: 80
        env:
          - name: Info__ContainerId
            valueFrom:
              fieldRef:
               fieldPath: metadata.name
          - name: Info__GrpcServiceUrl
            value: http://go-service:8080
          - name: ConnectionStrings__Postgres_Db
            value: "Host=blogging-db;Port=5432;Database=blogging;Username=dotnet;Password=superSecurePassword;"
            
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
  namespace: test-k8s-app
spec:
  type: LoadBalancer
  selector:
    app: dotnet-service
  ports:
    - port: 80
      targetPort: 80
      name: regular
    - port: 443
      targetPort: 443
      name: secure
