apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  type: LoadBalancer
  selector:
    app: dotnet-service
  ports:
  - port: 80
    targetPort: 80
    name: regular
  - port: 443
    targetPort: 443
    name: secure
