apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
  labels:
    app: go-service
spec:
    selector:
      matchLabels:
        app: go-service
    template:
      metadata:
        labels:
          app: go-service
      spec:
        containers:
          - name: go-service
            image: gerardohp/testk8s_grpc
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 8080
            # readinessProbe:
            #   exec:
            #     command: ["/bin/grpc_health_probe", "-addr=:8080"]
            resources:
              limits:
                memory: "128Mi"
                cpu: "200m"
            