apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-data
# namespace: test_k8s_app
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/gerardohernandez/test_k8s_app/pg-data
    type: DirectoryOrCreate
 # nfs:
 #   path: /tmp
 #   server: 172.17.0.2
